source    : era5
version   : 1.0.0
lat_samp   : 0.1
lon_samp   : 0.1
trajectory_type : eulerian
domain          : SEUS
campaign        : SEUS
surface_type    : land
version         : 1.0.1
lat_origin      : 34.25
lon_origin      : -87.25
datetime_origin : 2015-08-09T00:00
backward_duration : 0H
forward_duration : 120H
timestep        : domain_data
gradient_method : boundary
advection_velocity_sampling_method : domain_mean
sampling_mask   : land_only
averaging_width : 1.0
levels_method   : exponential
levels_number   : 250
levels_dzmin    : 20.0
levels_ztop     : 72000.0
version         : 1.0.0
export_format   : kpt
comment         : Forcing and initial conditions for Lagrangian case
author          : Thijs Heus
modifications   : First version
case            : n/a
adv_temp        : 0
adv_theta       : 1
adv_thetal      : 1
adv_qv          : 1
adv_qt          : 1
adv_rv          : 1
adv_rt          : 1
rad_temp        : 0
rad_theta       : 0
rad_thetal      : 0
forc_omega      : 0
forc_w          : 1
forc_geo        : 1
nudging_u       : 0
nudging_v       : 0
nudging_temp    : 0
nudging_theta   : 0
nudging_thetal  : 0
nudging_qv      : 0
nudging_qt      : 0
nudging_rv      : 0
nudging_rt      : 0
surfaceType     : land
surfaceForcing  : ts
surfaceForcingWind               : z0_traj